### ISSUE TITLE
Incorrect function signature of callback function libp2p.dial

### ISSUE THREAD

**Issue by shresthagrawal** [libp2p/js-libp2p-examples#15]
The function signature of callback function libp2p.dial at
[here](https://github.com/libp2p/js-libp2p-examples/blob/master/chat/nodejs/03-Muxing-Encryption/index.js#L42) is incorrect according to the [doc](https://github.com/libp2p/js-libp2p/blob/v0.25.2/README.md#libp2pdialpeer-callback).

Also it throws the below error even after correcting the signature for the latest release of js-libp2p.
```bash
/Users/shresthagrawal/Desktop/study/libp2p/my-chat/index2.js:44
         if (err) throw err
                  ^

Error: Dial was aborted
    at createError (/Users/shresthagrawal/Desktop/study/libp2p/my-chat/node_modules/err-code/index.js:4:44)
    at DIAL_ABORTED (/Users/shresthagrawal/Desktop/study/libp2p/my-chat/node_modules/libp2p/src/switch/errors.js:7:23)
    at Queue.abort (/Users/shresthagrawal/Desktop/study/libp2p/my-chat/node_modules/libp2p/src/switch/dialer/queue.js:144:21)
    at Queue.denylist (/Users/shresthagrawal/Desktop/study/libp2p/my-chat/node_modules/libp2p/src/switch/dialer/queue.js:169:10)
    at ClassIsWrapper.<anonymous> (/Users/shresthagrawal/Desktop/study/libp2p/my-chat/node_modules/libp2p/src/switch/dialer/queue.js:252:12)
    at Object.onceWrapper (events.js:284:20)
    at ClassIsWrapper.emit (events.js:196:13)
    at ClassIsWrapper.emit (/Users/shresthagrawal/Desktop/study/libp2p/my-chat/node_modules/libp2p/src/switch/connection/base.js:36:13)
    at ClassIsWrapper.close (/Users/shresthagrawal/Desktop/study/libp2p/my-chat/node_modules/libp2p/src/switch/connection/base.js:27:12)
    at /Users/shresthagrawal/Desktop/study/libp2p/my-chat/node_modules/libp2p/src/switch/connection/index.js:318:23
```

**Comment by jacobheun** [comment]
This should be correct now that the examples have been updated to 0.28.
