### ISSUE TITLE
Multiple errors in the build of the browser chat example.

### ISSUE THREAD

**Issue by Ankan0011** [libp2p/js-libp2p-examples#45]
After the npm clean-install of the browser based chat examples, I am getting error with parcel build issue whenever I am trying to run. Maybe downgrading the parcel version fixes the problem.

I am getting this error when i am trying to run the clean build of the examples.

Server running at http://localhost:1234 
🚨  /home/ankanghosh/jsbuild/master-code/js-libp2p-examples/chat/browser/08-End/index.js: Invalid Version: undefined
    at new SemVer (/home/ankanghosh/jsbuild/master-code/js-libp2p-examples/chat/browser/node_modules/@babel/preset-env/node_modules/semver/semver.js:314:11)
    at compare (/home/ankanghosh/jsbuild/master-code/js-libp2p-examples/chat/browser/node_modules/@babel/preset-env/node_modules/semver/semver.js:647:10)
    at lt (/home/ankanghosh/jsbuild/master-code/js-libp2p-examples/chat/browser/node_modules/@babel/preset-env/node_modules/semver/semver.js:688:10)
    at /home/ankanghosh/jsbuild/master-code/js-libp2p-examples/chat/browser/node_modules/@babel/preset-env/lib/index.js:280:22
    at Object.default (/home/ankanghosh/jsbuild/master-code/js-libp2p-examples/chat/browser/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12)
    at getEnvPlugins (/home/ankanghosh/jsbuild/master-code/js-libp2p-examples/chat/browser/node_modules/parcel/src/transforms/babel/env.js:62:34)

Can you please let me know which version of node is required to be used here ?

**Comment by chrisjowen** [comment]
Also faced this issue on node v14.* downgrading to v12.18.4 seemeed to work but facing another issue now.
